#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    vrt:
      type: string
      example:  "8"
    type:
      type: string
      example: ""
      required: false
    line:
      type: number
      example : 1
    name:
      type: string
      example: Administratio
    unit:
      type: string
      example: Unit
    amount:
      type: number
      example : 45678
    price:
      type: number
      example : 45678
    quantity:
      type: number
      example : 1
    vat:
      type: number
      example : 3654.0000
    total:
      type: number
      example : 3654.0000
    c0:
      type: string
      example : "3654.0000"
    c1:
      type: string
      example : "3654.0000"
    c2:
      type: string
      example : "3654.0000"
    c3:
      type: string
      example : "3654.0000"