{
  "headers": {
    "direction": "Outbound",
    "externalsystem": "SAP",
    "correlationid": "3334444",
    "filetype": "vendor-master",
    "filename": "test",
    "fileextension": "csv",
    "x-client-id": "f23334",
    "x-client-secret": "dfgg444",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.30.1",
    "accept": "*/*",
    "postman-token": "8710348f-9258-418d-8ad4-6cbd496c6558",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "1636"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/v1/create-invoice",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/create-invoice",
  "listenerPath": "/api/v1/*",
  "relativePath": "/api/v1/create-invoice",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/v1/create-invoice",
  "rawRequestPath": "/api/v1/create-invoice",
  "remoteAddress": "/127.0.0.1:61395",
  "requestPath": "/api/v1/create-invoice"
}